apiVersion: v1
kind: Pod
metadata:
  name: simple-echo
spec:
  containers:
    - name: hello-server-one
      image: leafy8050/spring-server:latest
      env:
        - name: MY_NAME
          value: ONE
      ports:
        - containerPort: 8080